// Periodic Table Explorer - JavaScript كامل مع جميع العناصر 118 والمعلومات المحدثة

const elements = {
    // ------------------- الدورة الأولى -------------------
    H: {
        name: "Hydrogen",
        state: "Gas",
        atomicNumber: 1,
        massNumber: 1,
        atomicMass: "1.008",
        protons: 1,
        neutrons: 0,
        electrons: 1,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Non-metal",
        period: 1,
        info: "Lightest element. Used in fuel cells. Most abundant element in the universe."
    },
    He: {
        name: "Helium",
        state: "Gas",
        atomicNumber: 2,
        massNumber: 4,
        atomicMass: "4.0026",
        protons: 2,
        neutrons: 2,
        electrons: 2,
        valency: "0",
        block: "s-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 1,
        info: "Used in balloons and cooling systems. Second lightest element."
    },

    // ------------------- الدورة الثانية -------------------
    Li: {
        name: "Lithium",
        state: "Solid",
        atomicNumber: 3,
        massNumber: 7,
        atomicMass: "6.94",
        protons: 3,
        neutrons: 4,
        electrons: 3,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 2,
        info: "Used in batteries for phones and electric cars. Lightest metal."
    },
    Be: {
        name: "Beryllium",
        state: "Solid",
        atomicNumber: 4,
        massNumber: 9,
        atomicMass: "9.0122",
        protons: 4,
        neutrons: 5,
        electrons: 4,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 2,
        info: "Used in aerospace and nuclear reactors."
    },
    B: {
        name: "Boron",
        state: "Solid",
        atomicNumber: 5,
        massNumber: 11,
        atomicMass: "10.81",
        protons: 5,
        neutrons: 6,
        electrons: 5,
        valency: "3",
        block: "p-block",
        group: "3A",
        groupName: "Metalloid",
        period: 2,
        info: "Used in glass and detergents. Essential for plant growth."
    },
    C: {
        name: "Carbon",
        state: "Solid",
        atomicNumber: 6,
        massNumber: 12,
        atomicMass: "12.011",
        protons: 6,
        neutrons: 6,
        electrons: 6,
        valency: "4",
        block: "p-block",
        group: "4A",
        groupName: "Non-metal",
        period: 2,
        info: "Basis of all organic life. Exists as diamond, graphite, and graphene."
    },
    N: {
        name: "Nitrogen",
        state: "Gas",
        atomicNumber: 7,
        massNumber: 14,
        atomicMass: "14.007",
        protons: 7,
        neutrons: 7,
        electrons: 7,
        valency: "3,5",
        block: "p-block",
        group: "5A",
        groupName: "Non-metal",
        period: 2,
        info: "Makes up 78% of Earth's atmosphere. Used in fertilizers."
    },
    O: {
        name: "Oxygen",
        state: "Gas",
        atomicNumber: 8,
        massNumber: 16,
        atomicMass: "15.999",
        protons: 8,
        neutrons: 8,
        electrons: 8,
        valency: "2",
        block: "p-block",
        group: "6A",
        groupName: "Non-metal",
        period: 2,
        info: "Essential for respiration. Third most abundant element in the universe."
    },
    F: {
        name: "Fluorine",
        state: "Gas",
        atomicNumber: 9,
        massNumber: 19,
        atomicMass: "18.998",
        protons: 9,
        neutrons: 10,
        electrons: 9,
        valency: "1",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 2,
        info: "Most reactive element. Used in toothpaste and refrigerants."
    },
    Ne: {
        name: "Neon",
        state: "Gas",
        atomicNumber: 10,
        massNumber: 20,
        atomicMass: "20.180",
        protons: 10,
        neutrons: 10,
        electrons: 10,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 2,
        info: "Used in neon signs and lights. Glows red-orange when electrified."
    },

    // ------------------- الدورة الثالثة -------------------
    Na: {
        name: "Sodium",
        state: "Solid",
        atomicNumber: 11,
        massNumber: 23,
        atomicMass: "22.990",
        protons: 11,
        neutrons: 12,
        electrons: 11,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 3,
        info: "Essential for nerve function. Used in table salt (NaCl)."
    },
    Mg: {
        name: "Magnesium",
        state: "Solid",
        atomicNumber: 12,
        massNumber: 24,
        atomicMass: "24.305",
        protons: 12,
        neutrons: 12,
        electrons: 12,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 3,
        info: "Essential for muscle function. Used in lightweight alloys."
    },
    Al: {
        name: "Aluminum",
        state: "Solid",
        atomicNumber: 13,
        massNumber: 27,
        atomicMass: "26.982",
        protons: 13,
        neutrons: 14,
        electrons: 13,
        valency: "3",
        block: "p-block",
        group: "3A",
        groupName: "Post-transition Metal",
        period: 3,
        info: "Most abundant metal in Earth's crust. Used in cans and aircraft."
    },
    Si: {
        name: "Silicon",
        state: "Solid",
        atomicNumber: 14,
        massNumber: 28,
        atomicMass: "28.085",
        protons: 14,
        neutrons: 14,
        electrons: 14,
        valency: "4",
        block: "p-block",
        group: "4A",
        groupName: "Metalloid",
        period: 3,
        info: "Foundation of modern electronics. Used in computer chips."
    },
    P: {
        name: "Phosphorus",
        state: "Solid",
        atomicNumber: 15,
        massNumber: 31,
        atomicMass: "30.974",
        protons: 15,
        neutrons: 16,
        electrons: 15,
        valency: "3,5",
        block: "p-block",
        group: "5A",
        groupName: "Non-metal",
        period: 3,
        info: "Essential for DNA and energy transfer in cells."
    },
    S: {
        name: "Sulfur",
        state: "Solid",
        atomicNumber: 16,
        massNumber: 32,
        atomicMass: "32.06",
        protons: 16,
        neutrons: 16,
        electrons: 16,
        valency: "2,4,6",
        block: "p-block",
        group: "6A",
        groupName: "Non-metal",
        period: 3,
        info: "Used in matches and gunpowder. Smells like rotten eggs."
    },
    Cl: {
        name: "Chlorine",
        state: "Gas",
        atomicNumber: 17,
        massNumber: 35,
        atomicMass: "35.45",
        protons: 17,
        neutrons: 18,
        electrons: 17,
        valency: "1,3,5,7",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 3,
        info: "Used in water purification and cleaning products."
    },
    Ar: {
        name: "Argon",
        state: "Gas",
        atomicNumber: 18,
        massNumber: 40,
        atomicMass: "39.948",
        protons: 18,
        neutrons: 22,
        electrons: 18,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 3,
        info: "Used in light bulbs to protect filaments. Third most abundant gas in atmosphere."
    },

    // ------------------- الدورة الرابعة -------------------
    K: {
        name: "Potassium",
        state: "Solid",
        atomicNumber: 19,
        massNumber: 39,
        atomicMass: "39.098",
        protons: 19,
        neutrons: 20,
        electrons: 19,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 4,
        info: "Essential for heart and muscle function. Found in bananas."
    },
    Ca: {
        name: "Calcium",
        state: "Solid",
        atomicNumber: 20,
        massNumber: 40,
        atomicMass: "40.078",
        protons: 20,
        neutrons: 20,
        electrons: 20,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 4,
        info: "Essential for bones and teeth. Found in milk and dairy products."
    },
    Sc: {
        name: "Scandium",
        state: "Solid",
        atomicNumber: 21,
        massNumber: 45,
        atomicMass: "44.956",
        protons: 21,
        neutrons: 24,
        electrons: 21,
        valency: "3",
        block: "d-block",
        group: "3B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used in aerospace components and high-intensity lights."
    },
    Ti: {
        name: "Titanium",
        state: "Solid",
        atomicNumber: 22,
        massNumber: 48,
        atomicMass: "47.867",
        protons: 22,
        neutrons: 26,
        electrons: 22,
        valency: "2,3,4",
        block: "d-block",
        group: "4B",
        groupName: "Transition Metal",
        period: 4,
        info: "Strong and lightweight. Used in aircraft and medical implants."
    },
    V: {
        name: "Vanadium",
        state: "Solid",
        atomicNumber: 23,
        massNumber: 51,
        atomicMass: "50.942",
        protons: 23,
        neutrons: 28,
        electrons: 23,
        valency: "2,3,4,5",
        block: "d-block",
        group: "5B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used in steel alloys to make them stronger."
    },
    Cr: {
        name: "Chromium",
        state: "Solid",
        atomicNumber: 24,
        massNumber: 52,
        atomicMass: "51.996",
        protons: 24,
        neutrons: 28,
        electrons: 24,
        valency: "2,3,6",
        block: "d-block",
        group: "6B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used for chrome plating and stainless steel production."
    },
    Mn: {
        name: "Manganese",
        state: "Solid",
        atomicNumber: 25,
        massNumber: 55,
        atomicMass: "54.938",
        protons: 25,
        neutrons: 30,
        electrons: 25,
        valency: "2,3,4,6,7",
        block: "d-block",
        group: "7B",
        groupName: "Transition Metal",
        period: 4,
        info: "Essential for steel production and vitamin absorption."
    },
    Fe: {
        name: "Iron",
        state: "Solid",
        atomicNumber: 26,
        massNumber: 56,
        atomicMass: "55.845",
        protons: 26,
        neutrons: 30,
        electrons: 26,
        valency: "2,3",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 4,
        info: "Most common metal on Earth. Essential for blood (hemoglobin)."
    },
    Co: {
        name: "Cobalt",
        state: "Solid",
        atomicNumber: 27,
        massNumber: 59,
        atomicMass: "58.933",
        protons: 27,
        neutrons: 32,
        electrons: 27,
        valency: "2,3",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used in batteries and gives blue color to glass and ceramics."
    },
    Ni: {
        name: "Nickel",
        state: "Solid",
        atomicNumber: 28,
        massNumber: 59,
        atomicMass: "58.693",
        protons: 28,
        neutrons: 31,
        electrons: 28,
        valency: "2,3",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used in stainless steel and coins. Magnetic at room temperature."
    },
    Cu: {
        name: "Copper",
        state: "Solid",
        atomicNumber: 29,
        massNumber: 64,
        atomicMass: "63.546",
        protons: 29,
        neutrons: 35,
        electrons: 29,
        valency: "1,2",
        block: "d-block",
        group: "1B",
        groupName: "Transition Metal",
        period: 4,
        info: "Excellent conductor of electricity. Used in electrical wiring and pipes."
    },
    Zn: {
        name: "Zinc",
        state: "Solid",
        atomicNumber: 30,
        massNumber: 65,
        atomicMass: "65.38",
        protons: 30,
        neutrons: 35,
        electrons: 30,
        valency: "2",
        block: "d-block",
        group: "2B",
        groupName: "Transition Metal",
        period: 4,
        info: "Used to galvanize steel. Essential for immune system."
    },
    Ga: {
        name: "Gallium",
        state: "Solid",
        atomicNumber: 31,
        massNumber: 70,
        atomicMass: "69.723",
        protons: 31,
        neutrons: 39,
        electrons: 31,
        valency: "3",
        block: "p-block",
        group: "3A",
        groupName: "Post-transition Metal",
        period: 4,
        info: "Melts in your hand. Used in LEDs and semiconductors."
    },
    Ge: {
        name: "Germanium",
        state: "Solid",
        atomicNumber: 32,
        massNumber: 73,
        atomicMass: "72.63",
        protons: 32,
        neutrons: 41,
        electrons: 32,
        valency: "4",
        block: "p-block",
        group: "4A",
        groupName: "Metalloid",
        period: 4,
        info: "Used in fiber optics and infrared optics."
    },
    As: {
        name: "Arsenic",
        state: "Solid",
        atomicNumber: 33,
        massNumber: 75,
        atomicMass: "74.922",
        protons: 33,
        neutrons: 42,
        electrons: 33,
        valency: "3,5",
        block: "p-block",
        group: "5A",
        groupName: "Metalloid",
        period: 4,
        info: "Toxic in large amounts. Used in semiconductors and wood preservatives."
    },
    Se: {
        name: "Selenium",
        state: "Solid",
        atomicNumber: 34,
        massNumber: 79,
        atomicMass: "78.96",
        protons: 34,
        neutrons: 45,
        electrons: 34,
        valency: "2,4,6",
        block: "p-block",
        group: "6A",
        groupName: "Non-metal",
        period: 4,
        info: "Essential nutrient. Used in photocopiers and solar cells."
    },
    Br: {
        name: "Bromine",
        state: "Liquid",
        atomicNumber: 35,
        massNumber: 80,
        atomicMass: "79.904",
        protons: 35,
        neutrons: 45,
        electrons: 35,
        valency: "1,3,5,7",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 4,
        info: "Only non-metallic element liquid at room temperature. Used in flame retardants."
    },
    Kr: {
        name: "Krypton",
        state: "Gas",
        atomicNumber: 36,
        massNumber: 84,
        atomicMass: "83.798",
        protons: 36,
        neutrons: 48,
        electrons: 36,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 4,
        info: "Used in high-performance light bulbs and lasers."
    },

    // ------------------- الدورة الخامسة -------------------
    Rb: {
        name: "Rubidium",
        state: "Solid",
        atomicNumber: 37,
        massNumber: 85,
        atomicMass: "85.468",
        protons: 37,
        neutrons: 48,
        electrons: 37,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 5,
        info: "Used in atomic clocks and research."
    },
    Sr: {
        name: "Strontium",
        state: "Solid",
        atomicNumber: 38,
        massNumber: 88,
        atomicMass: "87.62",
        protons: 38,
        neutrons: 50,
        electrons: 38,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 5,
        info: "Used in fireworks for red color and in toothpaste for sensitive teeth."
    },
    Y: {
        name: "Yttrium",
        state: "Solid",
        atomicNumber: 39,
        massNumber: 89,
        atomicMass: "88.906",
        protons: 39,
        neutrons: 50,
        electrons: 39,
        valency: "3",
        block: "d-block",
        group: "3B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in LEDs and superconductors."
    },
    Zr: {
        name: "Zirconium",
        state: "Solid",
        atomicNumber: 40,
        massNumber: 91,
        atomicMass: "91.224",
        protons: 40,
        neutrons: 51,
        electrons: 40,
        valency: "4",
        block: "d-block",
        group: "4B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in nuclear reactors and ceramic knives."
    },
    Nb: {
        name: "Niobium",
        state: "Solid",
        atomicNumber: 41,
        massNumber: 93,
        atomicMass: "92.906",
        protons: 41,
        neutrons: 52,
        electrons: 41,
        valency: "3,5",
        block: "d-block",
        group: "5B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in superconducting magnets and steel alloys."
    },
    Mo: {
        name: "Molybdenum",
        state: "Solid",
        atomicNumber: 42,
        massNumber: 96,
        atomicMass: "95.95",
        protons: 42,
        neutrons: 54,
        electrons: 42,
        valency: "2,3,4,5,6",
        block: "d-block",
        group: "6B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in steel alloys and as a catalyst in oil refineries."
    },
    Tc: {
        name: "Technetium",
        state: "Solid",
        atomicNumber: 43,
        massNumber: 98,
        atomicMass: "98",
        protons: 43,
        neutrons: 55,
        electrons: 43,
        valency: "4,6,7",
        block: "d-block",
        group: "7B",
        groupName: "Transition Metal",
        period: 5,
        info: "First artificially made element. Used in medical imaging."
    },
    Ru: {
        name: "Ruthenium",
        state: "Solid",
        atomicNumber: 44,
        massNumber: 101,
        atomicMass: "101.07",
        protons: 44,
        neutrons: 57,
        electrons: 44,
        valency: "2,3,4,6,8",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in electronics and as a catalyst."
    },
    Rh: {
        name: "Rhodium",
        state: "Solid",
        atomicNumber: 45,
        massNumber: 103,
        atomicMass: "102.91",
        protons: 45,
        neutrons: 58,
        electrons: 45,
        valency: "2,3,4",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in catalytic converters and jewelry plating. Very expensive."
    },
    Pd: {
        name: "Palladium",
        state: "Solid",
        atomicNumber: 46,
        massNumber: 106,
        atomicMass: "106.42",
        protons: 46,
        neutrons: 60,
        electrons: 46,
        valency: "2,4",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in catalytic converters, electronics, and hydrogen storage."
    },
    Ag: {
        name: "Silver",
        state: "Solid",
        atomicNumber: 47,
        massNumber: 108,
        atomicMass: "107.87",
        protons: 47,
        neutrons: 61,
        electrons: 47,
        valency: "1",
        block: "d-block",
        group: "1B",
        groupName: "Transition Metal",
        period: 5,
        info: "Best conductor of electricity. Used in jewelry and photography."
    },
    Cd: {
        name: "Cadmium",
        state: "Solid",
        atomicNumber: 48,
        massNumber: 112,
        atomicMass: "112.41",
        protons: 48,
        neutrons: 64,
        electrons: 48,
        valency: "2",
        block: "d-block",
        group: "2B",
        groupName: "Transition Metal",
        period: 5,
        info: "Used in batteries and nuclear reactors. Toxic."
    },
    In: {
        name: "Indium",
        state: "Solid",
        atomicNumber: 49,
        massNumber: 115,
        atomicMass: "114.82",
        protons: 49,
        neutrons: 66,
        electrons: 49,
        valency: "3",
        block: "p-block",
        group: "3A",
        groupName: "Post-transition Metal",
        period: 5,
        info: "Used in touch screens and solar panels."
    },
    Sn: {
        name: "Tin",
        state: "Solid",
        atomicNumber: 50,
        massNumber: 119,
        atomicMass: "118.71",
        protons: 50,
        neutrons: 69,
        electrons: 50,
        valency: "2,4",
        block: "p-block",
        group: "4A",
        groupName: "Post-transition Metal",
        period: 5,
        info: "Used in solder and food cans. Can 'tin cry' when bent."
    },
    Sb: {
        name: "Antimony",
        state: "Solid",
        atomicNumber: 51,
        massNumber: 122,
        atomicMass: "121.76",
        protons: 51,
        neutrons: 71,
        electrons: 51,
        valency: "3,5",
        block: "p-block",
        group: "5A",
        groupName: "Metalloid",
        period: 5,
        info: "Used in flame retardants and alloys."
    },
    Te: {
        name: "Tellurium",
        state: "Solid",
        atomicNumber: 52,
        massNumber: 128,
        atomicMass: "127.60",
        protons: 52,
        neutrons: 76,
        electrons: 52,
        valency: "2,4,6",
        block: "p-block",
        group: "6A",
        groupName: "Metalloid",
        period: 5,
        info: "Used in solar panels and rewritable CDs/DVDs."
    },
    I: {
        name: "Iodine",
        state: "Solid",
        atomicNumber: 53,
        massNumber: 127,
        atomicMass: "126.90",
        protons: 53,
        neutrons: 74,
        electrons: 53,
        valency: "1,3,5,7",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 5,
        info: "Essential for thyroid function. Used as antiseptic."
    },
    Xe: {
        name: "Xenon",
        state: "Gas",
        atomicNumber: 54,
        massNumber: 131,
        atomicMass: "131.29",
        protons: 54,
        neutrons: 77,
        electrons: 54,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 5,
        info: "Used in flash lamps and ion thrusters for spacecraft."
    },

    // ------------------- الدورة السادسة -------------------
    Cs: {
        name: "Cesium",
        state: "Solid",
        atomicNumber: 55,
        massNumber: 133,
        atomicMass: "132.91",
        protons: 55,
        neutrons: 78,
        electrons: 55,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 6,
        info: "Most reactive metal. Used in atomic clocks."
    },
    Ba: {
        name: "Barium",
        state: "Solid",
        atomicNumber: 56,
        massNumber: 137,
        atomicMass: "137.33",
        protons: 56,
        neutrons: 81,
        electrons: 56,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 6,
        info: "Used in X-ray imaging of digestive system."
    },
    La: {
        name: "Lanthanum",
        state: "Solid",
        atomicNumber: 57,
        massNumber: 139,
        atomicMass: "138.91",
        protons: 57,
        neutrons: 82,
        electrons: 57,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in camera lenses and carbon arc lights."
    },
    Ce: {
        name: "Cerium",
        state: "Solid",
        atomicNumber: 58,
        massNumber: 140,
        atomicMass: "140.12",
        protons: 58,
        neutrons: 82,
        electrons: 58,
        valency: "3,4",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Most abundant rare earth element. Used in glass polishing."
    },
    Pr: {
        name: "Praseodymium",
        state: "Solid",
        atomicNumber: 59,
        massNumber: 141,
        atomicMass: "140.91",
        protons: 59,
        neutrons: 82,
        electrons: 59,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in aircraft engines and welding goggles."
    },
    Nd: {
        name: "Neodymium",
        state: "Solid",
        atomicNumber: 60,
        massNumber: 144,
        atomicMass: "144.24",
        protons: 60,
        neutrons: 84,
        electrons: 60,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in powerful magnets for headphones and motors."
    },
    Pm: {
        name: "Promethium",
        state: "Solid",
        atomicNumber: 61,
        massNumber: 145,
        atomicMass: "145",
        protons: 61,
        neutrons: 84,
        electrons: 61,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Radioactive. Used in pacemakers and spacecraft."
    },
    Sm: {
        name: "Samarium",
        state: "Solid",
        atomicNumber: 62,
        massNumber: 150,
        atomicMass: "150.36",
        protons: 62,
        neutrons: 88,
        electrons: 62,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in cancer treatment and nuclear reactors."
    },
    Eu: {
        name: "Europium",
        state: "Solid",
        atomicNumber: 63,
        massNumber: 152,
        atomicMass: "151.96",
        protons: 63,
        neutrons: 89,
        electrons: 63,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in Euro banknotes for anti-counterfeiting."
    },
    Gd: {
        name: "Gadolinium",
        state: "Solid",
        atomicNumber: 64,
        massNumber: 157,
        atomicMass: "157.25",
        protons: 64,
        neutrons: 93,
        electrons: 64,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in MRI contrast agents and nuclear reactors."
    },
    Tb: {
        name: "Terbium",
        state: "Solid",
        atomicNumber: 65,
        massNumber: 159,
        atomicMass: "158.93",
        protons: 65,
        neutrons: 94,
        electrons: 65,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in green phosphors for TV screens."
    },
    Dy: {
        name: "Dysprosium",
        state: "Solid",
        atomicNumber: 66,
        massNumber: 162,
        atomicMass: "162.50",
        protons: 66,
        neutrons: 96,
        electrons: 66,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in nuclear reactors and data storage."
    },
    Ho: {
        name: "Holmium",
        state: "Solid",
        atomicNumber: 67,
        massNumber: 165,
        atomicMass: "164.93",
        protons: 67,
        neutrons: 98,
        electrons: 67,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in lasers and nuclear reactors."
    },
    Er: {
        name: "Erbium",
        state: "Solid",
        atomicNumber: 68,
        massNumber: 167,
        atomicMass: "167.26",
        protons: 68,
        neutrons: 99,
        electrons: 68,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in fiber optics and lasers."
    },
    Tm: {
        name: "Thulium",
        state: "Solid",
        atomicNumber: 69,
        massNumber: 169,
        atomicMass: "168.93",
        protons: 69,
        neutrons: 100,
        electrons: 69,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in portable X-ray machines."
    },
    Yb: {
        name: "Ytterbium",
        state: "Solid",
        atomicNumber: 70,
        massNumber: 173,
        atomicMass: "173.05",
        protons: 70,
        neutrons: 103,
        electrons: 70,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in stress gauges and lasers."
    },
    Lu: {
        name: "Lutetium",
        state: "Solid",
        atomicNumber: 71,
        massNumber: 175,
        atomicMass: "174.97",
        protons: 71,
        neutrons: 104,
        electrons: 71,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Lanthanide",
        period: 6,
        info: "Used in PET scanners and catalysts."
    },
    Hf: {
        name: "Hafnium",
        state: "Solid",
        atomicNumber: 72,
        massNumber: 178,
        atomicMass: "178.49",
        protons: 72,
        neutrons: 106,
        electrons: 72,
        valency: "4",
        block: "d-block",
        group: "4B",
        groupName: "Transition Metal",
        period: 6,
        info: "Used in nuclear reactors and microchips."
    },
    Ta: {
        name: "Tantalum",
        state: "Solid",
        atomicNumber: 73,
        massNumber: 181,
        atomicMass: "180.95",
        protons: 73,
        neutrons: 108,
        electrons: 73,
        valency: "5",
        block: "d-block",
        group: "5B",
        groupName: "Transition Metal",
        period: 6,
        info: "Used in capacitors for electronics and surgical implants."
    },
    W: {
        name: "Tungsten",
        state: "Solid",
        atomicNumber: 74,
        massNumber: 184,
        atomicMass: "183.84",
        protons: 74,
        neutrons: 110,
        electrons: 74,
        valency: "2,3,4,5,6",
        block: "d-block",
        group: "6B",
        groupName: "Transition Metal",
        period: 6,
        info: "Highest melting point of all metals. Used in light bulb filaments."
    },
    Re: {
        name: "Rhenium",
        state: "Solid",
        atomicNumber: 75,
        massNumber: 186,
        atomicMass: "186.21",
        protons: 75,
        neutrons: 111,
        electrons: 75,
        valency: "2,3,4,5,6,7",
        block: "d-block",
        group: "7B",
        groupName: "Transition Metal",
        period: 6,
        info: "Used in jet engines and thermocouples."
    },
    Os: {
        name: "Osmium",
        state: "Solid",
        atomicNumber: 76,
        massNumber: 190,
        atomicMass: "190.23",
        protons: 76,
        neutrons: 114,
        electrons: 76,
        valency: "2,3,4,6,8",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 6,
        info: "Densest natural element. Used in fountain pen tips."
    },
    Ir: {
        name: "Iridium",
        state: "Solid",
        atomicNumber: 77,
        massNumber: 192,
        atomicMass: "192.22",
        protons: 77,
        neutrons: 115,
        electrons: 77,
        valency: "3,4",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 6,
        info: "Most corrosion-resistant metal. Found in dinosaur extinction layer."
    },
    Pt: {
        name: "Platinum",
        state: "Solid",
        atomicNumber: 78,
        massNumber: 195,
        atomicMass: "195.08",
        protons: 78,
        neutrons: 117,
        electrons: 78,
        valency: "2,4",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 6,
        info: "Used in catalytic converters and jewelry."
    },
    Au: {
        name: "Gold",
        state: "Solid",
        atomicNumber: 79,
        massNumber: 197,
        atomicMass: "196.97",
        protons: 79,
        neutrons: 118,
        electrons: 79,
        valency: "1,3",
        block: "d-block",
        group: "1B",
        groupName: "Transition Metal",
        period: 6,
        info: "Does not tarnish. Used in electronics and currency."
    },
    Hg: {
        name: "Mercury",
        state: "Liquid",
        atomicNumber: 80,
        massNumber: 201,
        atomicMass: "200.59",
        protons: 80,
        neutrons: 121,
        electrons: 80,
        valency: "1,2",
        block: "d-block",
        group: "2B",
        groupName: "Transition Metal",
        period: 6,
        info: "Only metal liquid at room temperature. Used in thermometers."
    },
    Tl: {
        name: "Thallium",
        state: "Solid",
        atomicNumber: 81,
        massNumber: 204,
        atomicMass: "204.38",
        protons: 81,
        neutrons: 123,
        electrons: 81,
        valency: "1,3",
        block: "p-block",
        group: "3A",
        groupName: "Post-transition Metal",
        period: 6,
        info: "Used in infrared detectors and medical imaging."
    },
    Pb: {
        name: "Lead",
        state: "Solid",
        atomicNumber: 82,
        massNumber: 207,
        atomicMass: "207.2",
        protons: 82,
        neutrons: 125,
        electrons: 82,
        valency: "2,4",
        block: "p-block",
        group: "4A",
        groupName: "Post-transition Metal",
        period: 6,
        info: "Used in car batteries and radiation shielding."
    },
    Bi: {
        name: "Bismuth",
        state: "Solid",
        atomicNumber: 83,
        massNumber: 209,
        atomicMass: "208.98",
        protons: 83,
        neutrons: 126,
        electrons: 83,
        valency: "3,5",
        block: "p-block",
        group: "5A",
        groupName: "Post-transition Metal",
        period: 6,
        info: "Forms beautiful crystals. Used in stomach medicine."
    },
    Po: {
        name: "Polonium",
        state: "Solid",
        atomicNumber: 84,
        massNumber: 209,
        atomicMass: "209",
        protons: 84,
        neutrons: 125,
        electrons: 84,
        valency: "2,4",
        block: "p-block",
        group: "6A",
        groupName: "Metalloid",
        period: 6,
        info: "Highly radioactive. Used in anti-static brushes."
    },
    At: {
        name: "Astatine",
        state: "Solid",
        atomicNumber: 85,
        massNumber: 210,
        atomicMass: "210",
        protons: 85,
        neutrons: 125,
        electrons: 85,
        valency: "1,3,5,7",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 6,
        info: "Rarest natural element. Used in cancer research."
    },
    Rn: {
        name: "Radon",
        state: "Gas",
        atomicNumber: 86,
        massNumber: 222,
        atomicMass: "222",
        protons: 86,
        neutrons: 136,
        electrons: 86,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 6,
        info: "Radioactive. Second leading cause of lung cancer."
    },

    // ------------------- الدورة السابعة -------------------
    Fr: {
        name: "Francium",
        state: "Solid",
        atomicNumber: 87,
        massNumber: 223,
        atomicMass: "223",
        protons: 87,
        neutrons: 136,
        electrons: 87,
        valency: "1",
        block: "s-block",
        group: "1A",
        groupName: "Alkali Metal",
        period: 7,
        info: "Most unstable natural element. Less than 30g on Earth."
    },
    Ra: {
        name: "Radium",
        state: "Solid",
        atomicNumber: 88,
        massNumber: 226,
        atomicMass: "226",
        protons: 88,
        neutrons: 138,
        electrons: 88,
        valency: "2",
        block: "s-block",
        group: "2A",
        groupName: "Alkaline Earth Metal",
        period: 7,
        info: "Discovered by Marie Curie. Used in cancer treatment."
    },
    Ac: {
        name: "Actinium",
        state: "Solid",
        atomicNumber: 89,
        massNumber: 227,
        atomicMass: "227",
        protons: 89,
        neutrons: 138,
        electrons: 89,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in neutron sources and cancer treatment."
    },
    Th: {
        name: "Thorium",
        state: "Solid",
        atomicNumber: 90,
        massNumber: 232,
        atomicMass: "232.04",
        protons: 90,
        neutrons: 142,
        electrons: 90,
        valency: "4",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Potential future nuclear fuel. Used in gas mantles."
    },
    Pa: {
        name: "Protactinium",
        state: "Solid",
        atomicNumber: 91,
        massNumber: 231,
        atomicMass: "231.04",
        protons: 91,
        neutrons: 140,
        electrons: 91,
        valency: "4,5",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Rare and expensive. Used in scientific research."
    },
    U: {
        name: "Uranium",
        state: "Solid",
        atomicNumber: 92,
        massNumber: 238,
        atomicMass: "238.03",
        protons: 92,
        neutrons: 146,
        electrons: 92,
        valency: "3,4,5,6",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in nuclear power and weapons. Also in glass coloring."
    },
    Np: {
        name: "Neptunium",
        state: "Solid",
        atomicNumber: 93,
        massNumber: 237,
        atomicMass: "237",
        protons: 93,
        neutrons: 144,
        electrons: 93,
        valency: "4,5,6",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "First synthetic transuranium element. Used in neutron detectors."
    },
    Pu: {
        name: "Plutonium",
        state: "Solid",
        atomicNumber: 94,
        massNumber: 239,
        atomicMass: "239",
        protons: 94,
        neutrons: 145,
        electrons: 94,
        valency: "3,4,5,6",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in nuclear weapons and space probes. Very toxic."
    },
    Am: {
        name: "Americium",
        state: "Solid",
        atomicNumber: 95,
        massNumber: 243,
        atomicMass: "243",
        protons: 95,
        neutrons: 148,
        electrons: 95,
        valency: "3,4,5,6",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in smoke detectors. Glows blue under UV light."
    },
    Cm: {
        name: "Curium",
        state: "Solid",
        atomicNumber: 96,
        massNumber: 247,
        atomicMass: "247",
        protons: 96,
        neutrons: 151,
        electrons: 96,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in space probes and scientific research."
    },
    Bk: {
        name: "Berkelium",
        state: "Solid",
        atomicNumber: 97,
        massNumber: 247,
        atomicMass: "247",
        protons: 97,
        neutrons: 150,
        electrons: 97,
        valency: "3,4",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in research to create heavier elements."
    },
    Cf: {
        name: "Californium",
        state: "Solid",
        atomicNumber: 98,
        massNumber: 251,
        atomicMass: "251",
        protons: 98,
        neutrons: 153,
        electrons: 98,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Used in airport scanners and gold mining."
    },
    Es: {
        name: "Einsteinium",
        state: "Solid",
        atomicNumber: 99,
        massNumber: 252,
        atomicMass: "252",
        protons: 99,
        neutrons: 153,
        electrons: 99,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Named after Albert Einstein. Used in research."
    },
    Fm: {
        name: "Fermium",
        state: "Solid",
        atomicNumber: 100,
        massNumber: 257,
        atomicMass: "257",
        protons: 100,
        neutrons: 157,
        electrons: 100,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Discovered in hydrogen bomb debris."
    },
    Md: {
        name: "Mendelevium",
        state: "Solid",
        atomicNumber: 101,
        massNumber: 258,
        atomicMass: "258",
        protons: 101,
        neutrons: 157,
        electrons: 101,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Named after Dmitri Mendeleev."
    },
    No: {
        name: "Nobelium",
        state: "Solid",
        atomicNumber: 102,
        massNumber: 259,
        atomicMass: "259",
        protons: 102,
        neutrons: 157,
        electrons: 102,
        valency: "2,3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Named after Alfred Nobel. Used in research."
    },
    Lr: {
        name: "Lawrencium",
        state: "Solid",
        atomicNumber: 103,
        massNumber: 262,
        atomicMass: "262",
        protons: 103,
        neutrons: 159,
        electrons: 103,
        valency: "3",
        block: "f-block",
        group: "3B",
        groupName: "Actinide",
        period: 7,
        info: "Named after Ernest Lawrence."
    },
    Rf: {
        name: "Rutherfordium",
        state: "Solid",
        atomicNumber: 104,
        massNumber: 267,
        atomicMass: "267",
        protons: 104,
        neutrons: 163,
        electrons: 104,
        valency: "4",
        block: "d-block",
        group: "4B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Ernest Rutherford."
    },
    Db: {
        name: "Dubnium",
        state: "Solid",
        atomicNumber: 105,
        massNumber: 268,
        atomicMass: "268",
        protons: 105,
        neutrons: 163,
        electrons: 105,
        valency: "5",
        block: "d-block",
        group: "5B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Dubna, Russia."
    },
    Sg: {
        name: "Seaborgium",
        state: "Solid",
        atomicNumber: 106,
        massNumber: 269,
        atomicMass: "269",
        protons: 106,
        neutrons: 163,
        electrons: 106,
        valency: "6",
        block: "d-block",
        group: "6B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Glenn T. Seaborg."
    },
    Bh: {
        name: "Bohrium",
        state: "Solid",
        atomicNumber: 107,
        massNumber: 270,
        atomicMass: "270",
        protons: 107,
        neutrons: 163,
        electrons: 107,
        valency: "7",
        block: "d-block",
        group: "7B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Niels Bohr."
    },
    Hs: {
        name: "Hassium",
        state: "Solid",
        atomicNumber: 108,
        massNumber: 269,
        atomicMass: "269",
        protons: 108,
        neutrons: 161,
        electrons: 108,
        valency: "8",
        block: "d-block",
        group: "8B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Hesse, Germany."
    },
    Mt: {
        name: "Meitnerium",
        state: "Solid",
        atomicNumber: 109,
        massNumber: 278,
        atomicMass: "278",
        protons: 109,
        neutrons: 169,
        electrons: 109,
        valency: "8",
        block: "d-block",
        group: "8B",
        groupName: "Unknown",
        period: 7,
        info: "Named after Lise Meitner."
    },
    Ds: {
        name: "Darmstadtium",
        state: "Solid",
        atomicNumber: 110,
        massNumber: 281,
        atomicMass: "281",
        protons: 110,
        neutrons: 171,
        electrons: 110,
        valency: "8",
        block: "d-block",
        group: "8B",
        groupName: "Unknown",
        period: 7,
        info: "Named after Darmstadt, Germany."
    },
    Rg: {
        name: "Roentgenium",
        state: "Solid",
        atomicNumber: 111,
        massNumber: 282,
        atomicMass: "282",
        protons: 111,
        neutrons: 171,
        electrons: 111,
        valency: "3",
        block: "d-block",
        group: "1B",
        groupName: "Unknown",
        period: 7,
        info: "Named after Wilhelm Roentgen."
    },
    Cn: {
        name: "Copernicium",
        state: "Liquid",
        atomicNumber: 112,
        massNumber: 285,
        atomicMass: "285",
        protons: 112,
        neutrons: 173,
        electrons: 112,
        valency: "2",
        block: "d-block",
        group: "2B",
        groupName: "Transition Metal",
        period: 7,
        info: "Named after Nicolaus Copernicus."
    },
    Nh: {
        name: "Nihonium",
        state: "Solid",
        atomicNumber: 113,
        massNumber: 286,
        atomicMass: "286",
        protons: 113,
        neutrons: 173,
        electrons: 113,
        valency: "3",
        block: "p-block",
        group: "3A",
        groupName: "Unknown",
        period: 7,
        info: "Named after Japan (Nihon)."
    },
    Fl: {
        name: "Flerovium",
        state: "Solid",
        atomicNumber: 114,
        massNumber: 289,
        atomicMass: "289",
        protons: 114,
        neutrons: 175,
        electrons: 114,
        valency: "4",
        block: "p-block",
        group: "4A",
        groupName: "Unknown",
        period: 7,
        info: "Named after Flerov Laboratory in Russia."
    },
    Mc: {
        name: "Moscovium",
        state: "Solid",
        atomicNumber: 115,
        massNumber: 290,
        atomicMass: "290",
        protons: 115,
        neutrons: 175,
        electrons: 115,
        valency: "3",
        block: "p-block",
        group: "5A",
        groupName: "Unknown",
        period: 7,
        info: "Named after Moscow, Russia."
    },
    Lv: {
        name: "Livermorium",
        state: "Solid",
        atomicNumber: 116,
        massNumber: 293,
        atomicMass: "293",
        protons: 116,
        neutrons: 177,
        electrons: 116,
        valency: "4",
        block: "p-block",
        group: "6A",
        groupName: "Unknown",
        period: 7,
        info: "Named after Lawrence Livermore National Laboratory."
    },
    Ts: {
        name: "Tennessine",
        state: "Solid",
        atomicNumber: 117,
        massNumber: 294,
        atomicMass: "294",
        protons: 117,
        neutrons: 177,
        electrons: 117,
        valency: "3",
        block: "p-block",
        group: "7A",
        groupName: "Halogen",
        period: 7,
        info: "Named after Tennessee, USA."
    },
    Og: {
        name: "Oganesson",
        state: "Gas",
        atomicNumber: 118,
        massNumber: 294,
        atomicMass: "294",
        protons: 118,
        neutrons: 176,
        electrons: 118,
        valency: "0",
        block: "p-block",
        group: "8A",
        groupName: "Noble Gas",
        period: 7,
        info: "Named after Yuri Oganessian. Heaviest element discovered."
    }
};

// دوال البرنامج الرئيسية
function searchElement() {
    const input = document.getElementById('elementInput');
    let symbol = input.value.trim();

    if (symbol === '') {
        alert('Please enter an element symbol');
        return;
    }

    // تنسيق الرمز: أول حرف كبير والباقي صغير
    symbol = symbol.charAt(0).toUpperCase() + symbol.slice(1).toLowerCase();

    const element = elements[symbol];

    // إخفاء الأقسام القديمة
    document.getElementById('resultSection').classList.add('hidden');
    document.getElementById('againSection').classList.add('hidden');
    document.getElementById('thankYouSection').classList.add('hidden');

    if (element) {
        displayElementInfo(element, symbol);
        document.getElementById('resultSection').classList.remove('hidden');
        document.getElementById('againSection').classList.remove('hidden');
    } else {
        displayNotFound(symbol);
        document.getElementById('resultSection').classList.remove('hidden');
        document.getElementById('againSection').classList.remove('hidden');
    }
}

function displayElementInfo(element, symbol) {
    const resultSection = document.getElementById('resultSection');
    
    resultSection.innerHTML = `
        <div class="element-name">${element.name} (${symbol})</div>
        <div class="info-grid">
            <div class="info-item">
                <strong>State</strong>
                <span>${element.state}</span>
            </div>
            <div class="info-item">
                <strong>Atomic Number</strong>
                <span>${element.atomicNumber}</span>
            </div>
            <div class="info-item">
                <strong>Mass Number</strong>
                <span>${element.massNumber}</span>
            </div>
            <div class="info-item">
                <strong>Atomic Mass</strong>
                <span>${element.atomicMass} g/mol</span>
            </div>
            <div class="info-item">
                <strong>Protons</strong>
                <span>${element.protons}</span>
            </div>
            <div class="info-item">
                <strong>Neutrons</strong>
                <span>${element.neutrons}</span>
            </div>
            <div class="info-item">
                <strong>Electrons</strong>
                <span>${element.electrons}</span>
            </div>
            <div class="info-item">
                <strong>Valency</strong>
                <span>${element.valency}</span>
            </div>
            <div class="info-item">
                <strong>Block</strong>
                <span>${element.block}</span>
            </div>
            <div class="info-item">
                <strong>Group</strong>
                <span>${element.group}</span>
            </div>
            <div class="info-item">
                <strong>Group Name</strong>
                <span>${element.groupName}</span>
            </div>
            <div class="info-item">
                <strong>Period</strong>
                <span>${element.period}</span>
            </div>
        </div>
        <div class="special-info">
            <strong>Special Info</strong>
            <p>${element.info}</p>
        </div>
    `;
}

function displayNotFound(symbol) {
    const resultSection = document.getElementById('resultSection');
    
    resultSection.innerHTML = `
        <div class="not-found">
            ❌ Element "${symbol}" not found<br>
            <small style="color: #666; display: block; margin-top: 10px;">Please check the symbol and try again</small>
        </div>
    `;
}

function restart() {
    // إخفاء كل الأقسام
    document.getElementById('resultSection').classList.add('hidden');
    document.getElementById('againSection').classList.add('hidden');
    document.getElementById('thankYouSection').classList.add('hidden');
    
    // مسح حقل الإدخال
    document.getElementById('elementInput').value = '';
    
    // إعادة التركيز لحقل الإدخال
    document.getElementById('elementInput').focus();
    
    // إعادة تفعيل زر البحث لو كان معطل
    document.querySelector('button[onclick="searchElement()"]').disabled = false;
}

function stop() {
    // إخفاء الأقسام غير المرغوب فيها
    document.getElementById('resultSection').classList.add('hidden');
    document.getElementById('againSection').classList.add('hidden');
    
    // إظهار رسالة الشكر
    document.getElementById('thankYouSection').classList.remove('hidden');
    
    // تعطيل البحث
    document.querySelector('button[onclick="searchElement()"]').disabled = true;
}

// إضافة خاصية البحث بالضغط على Enter
document.getElementById('elementInput').addEventListener('keypress', function(e) {
    if (e.key === 'Enter') {
        searchElement();
    }
});



